config/routes.rb
Rails.application.routes.draw do

  resources :conexion
  get 'grupo/index'
  

   root 'welcome#index'

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conexion_controller.rb
class ConexionController < ApplicationController
def index
	@alumno = Alumno.all
end
def show
	@alumno = Alumno.find(params[:id])
end

def new
	@alumno = Alumno.new
end
#POST /alumnos
def create 
	@alumno = Alumno.new ({nombre: params[:alumno] [:nombre],
							carne: params[:alumno] [:carne],
							curso: params[:alumno] [:curso],
						  carrera: params[:alumno] [:carrera]})
	if @alumno.save
		redirect_to action: 'index'
	else
		render :new
	end
end
	
end

app/controllers/grupo_controller.rb
class GrupoController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conexion/index.html.erb
<h1 align="center">Alumnos Inscritos</h1>
<% @alumno.each do |alumno| %>

<div class="panel panel-default">
	<div class="panel-heading">
	Nombre: <%= alumno.nombre %>
	</div>
	<table class="table">
		  <tr>
		    <td>#</td>
		   	<td>Carne</td>
		    <td>Curso</td>
		    <td>Carrera</td>
		  </tr>
		    <tr>
		    <td><%= alumno.id %></td>
		    <td><%= alumno.carne%></td>
		    <td><%= alumno.curso%></td>
		    <td><%= alumno.carrera%></td>
		  </tr>
	</table>

</div>
<%end%>

app/views/conexion/new.html.erb
<h1>ingresar datos</h1>
<%= form_for @alumno, url: conexion_index_path do |f| %>
	<div class="field">
		<%= f.text_field :nombre, placeholder: "Nombre"%>
	</div>
	<div class="field">
		<%= f.text_field :carne, placeholder: "Numero_Carné"%>
	</div>

	<div class="field">
		<%= f.text_field :curso, placeholder: "Nombre_curso"%>
	</div>

	<div class="field">
		<%= f.text_field :carrera, placeholder: "Nombre_carrera"%>
	</div>
	<div class="class">
		<%= f.submit "ingresar"%>
	</div>

<% end %>

app/views/conexion/show.html.erb
<h1>Datos del Alumno</h1>
<div>
	<%= @alumno.nombre	%>
</div>
<div>
	<%= @alumno.carne %>
</div>
<div>
	<%= @alumno.curso %>
</div>
<div>
	<%= @alumno.carrera %>
</div>

app/views/grupo/index.html.erb
<center>
	<h1>Integrantes del grupo</h1>	
	

	<h1>Oscar Ariel Sapón</h1>
	<h1>Carné: 2290-09-14683</h1>	

	<h1>Marco Gerardo Chiroy Mucún</h1>
	<h1>Carné: 2290-09-8392</h1>



</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../">HOME</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/conexion/new">Agregar_Datos <span class="sr-only">(current)</span></a></li>
        <li><a href="/conexion">Mostrar_Datos</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">DESARROLLADORES<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="https://www.facebook.com/umgsolola/?fref=ts">Facebook</a></li>
            <li><a href="/grupo/index">Integrantes del Grupo</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="main container">

<%= yield %>

</div>


</body>
</html>

app/views/welcome/index.html.erb
<center>
<marquee>BIENVENIDOS A UMG SOLOLA</marquee>
</center>